language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t hferguson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hferguson/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstock
  region: "ca-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-115080985397"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"